# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]

jobs:
  test-and-npm-publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Update npm
        run: bunx npm install -g npm@latest # Ensure npm is up-to-date. Provenance requires v9.6.0 or higher.
      - name: Build
        run: bun run build
      - name: Test
        run: bun test

      # if the release is not a pre-release, publish to npm as latest
      - name: Publish
        if: github.event.release.prerelease == false
        run: npm publish --provenance # remove the --provenance flag if you don't want to use npm provenance, or having issues with it
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # if the release is a pre-release, publish to npm using the beta tag
      - name: Publish [beta]
        if: github.event.release.prerelease == true
        run: npm publish --tag beta --provenance # remove the --provenance flag if you don't want to use npm provenance, or having issues with it
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
